### PR TITLE
docker: create initial production image

### LINKED ISSUE #141: Create a production Dockerfile for move to Kubernetes
### Descriptive summary
As a first step towards moving this application towards GitLab AutoDevops and Kubernetes, we need a 'proper' production Docker setup that can be leveraged. This will likely not include things like nginx initially but focus solely on the application itself for now (puma, asset pipeline, etc.) That will come as a secondary effort.

### Rationale

H5 would be a good target for a first "real" Kubernetes app for us. This work is a starting point for that.

### PR DESCRIPTION
**Pull request by mcritchlow**
- Introduce a bin/docker-helper.sh script for managing local docker
usage
- Dockerfile is now the 'production' image in preparation for Kubernetes
- Dockerfile.development is the 'development' image
- docker-compose files are broken into a docker subdirectory. Again
usage of these files has hopefully been simplified by the introduction
of the helper script
- Bump nodejs in dev script to latest v10.x

Fixes #141

#### Local Checklist
- [x] Tests written and passing locally?
- [x] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [x] Configuration updated (if needed)?
- [x] Documentation updated (if needed)?

#### What does this PR do?
- Introduce a bin/docker-helper.sh script for managing local docker
usage
- Dockerfile is now the 'production' image in preparation for Kubernetes
- Dockerfile.development is the 'development' image
- docker-compose files are broken into a docker subdirectory. Again
usage of these files has hopefully been simplified by the introduction
of the helper script

##### Why are we doing this? Any context of related work?
References #141

#### Where should a reviewer start?
Ideally it would be great if both @VivianChu and @dt-ucsd can try this out locally and let me know a) if it works for you and b) if there's any edge cases or commonly used commands that should go in the helper script.

Note the `production` setup has several holes right now. It's not really usable locally since the production environment requires shibboleth. That's going to have to be sorted out in a later effort. This is largely about making a distinction between dev/prod that I/we can build on going forward.

@VivianChu @dt-ucsd  - please review

### CODE REVIEW

**Comment by VivianChu** [comment]
👍 @mcritchlow - I tried it out and it worked great.  Thanks

**Comment by mcritchlow** [comment]
@VivianChu - thanks for testing! Glad it works for you :)

**Comment by mcritchlow** [comment]
@VivianChu - Just FYI I've rebased this PR against master following the merge of the other PR.

**Comment by mcritchlow** [comment]
@dt-ucsd did you have a chance to take a peek at this yet? If not, or you don't have time, that's cool, just want to make sure it doesn't go stale.

**Pull request merged**
